name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Kramarich0
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Moscow
          config_theme: radical
          config_order: base.header, isocalendar, languages, lines, habits, wakatime, followup, achievements
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          plugin_lines: yes

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: languages, editors, os
          plugin_wakatime_limit: 5
          
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
